import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Theme from "@/components/custom/theme";
import { store } from "./store/store";
import { ReduxProvider } from "@/components/providers/reduxProvider";
import QueryProvider from "./providers/queryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} h-full antialiased`}>
      <body
        className={` antialiased transition-all`}
        // style={{ fontFamily: "var(--font-rubik)" }}
      >
        <QueryProvider>
          <div className="flex w-screen h-screen">
            <ReduxProvider>{children}</ReduxProvider>
          </div>
          <Theme />
        </QueryProvider>
      </body>
    </html>
  );
}
