name: Deploy Next.js to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node
     # 2. Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 3. Install dependencies
      - name: Install dependencies
        run: bun install

      # 4. Build Next.js app
      - name: Build Next.js
        run: bun run build

      # 5. Build Docker image
      - name: Build Docker Image
        run: docker build -t next-app .

      # 6. Save image
      - name: Save Docker image
        run: docker save next-app > next-app.tar

      # 7. Copy to VM
      - name: Copy to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "next-app.tar"
          target: "/home/azureuser/"

      # 8. Run on VM
      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker stop next_app || true
            docker rm next_app || true
            docker load < next-app.tar
            docker run -d -p 3000:3000 --name next_app next-app
