name: Deploy Next.js to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Next.js
        run: bun run build

      - name: Build Docker Image
        run: docker build -t next-app .

      - name: Save Docker image
        run: docker save next-app > next-app.tar

      - name: Copy to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "next-app.tar"
          target: "/home/Rashmika/app"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/Rashmika/app

            docker stop next_app || true
            docker rm next_app || true

            docker load < next-app.tar

            docker run -d \
              -p 3000:3000 \
              --name next_app \
              -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
              -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
              next-app
